apiVersion: v1
kind: Service
metadata:
  name: image-classification
spec:
  selector:
    app: image-classification
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer